
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 369;
const int acc_off_y = -85;
const int acc_off_z = 1189;
const float acc_scale_x = 16261.134776;
const float acc_scale_y = 16536.106451;
const float acc_scale_z = 16889.348388;

const int magn_off_x = 26;
const int magn_off_y = -103;
const int magn_off_z = -33;
const float magn_scale_x = 473.754506;
const float magn_scale_y = 480.391617;
const float magn_scale_z = 498.818439;

