# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dai', [dirname(__file__)])
        except ImportError:
            import _dai
            return _dai
        if fp is not None:
            try:
                _mod = imp.load_module('_dai', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _dai = swig_import_helper()
    del swig_import_helper
else:
    import _dai
del version_info
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class SwigPyIterator:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dai.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _dai.SwigPyIterator_value(self)
    def incr(self, n=1): return _dai.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _dai.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _dai.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _dai.SwigPyIterator_equal(self, *args)
    def copy(self): return _dai.SwigPyIterator_copy(self)
    def next(self): return _dai.SwigPyIterator_next(self)
    def __next__(self): return _dai.SwigPyIterator___next__(self)
    def previous(self): return _dai.SwigPyIterator_previous(self)
    def advance(self, *args): return _dai.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _dai.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _dai.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _dai.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _dai.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _dai.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _dai.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _dai.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _dai.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _dai.IntVector___nonzero__(self)
    def __bool__(self): return _dai.IntVector___bool__(self)
    def __len__(self): return _dai.IntVector___len__(self)
    def pop(self): return _dai.IntVector_pop(self)
    def __getslice__(self, *args): return _dai.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _dai.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _dai.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _dai.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _dai.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _dai.IntVector___setitem__(self, *args)
    def append(self, *args): return _dai.IntVector_append(self, *args)
    def empty(self): return _dai.IntVector_empty(self)
    def size(self): return _dai.IntVector_size(self)
    def clear(self): return _dai.IntVector_clear(self)
    def swap(self, *args): return _dai.IntVector_swap(self, *args)
    def get_allocator(self): return _dai.IntVector_get_allocator(self)
    def begin(self): return _dai.IntVector_begin(self)
    def end(self): return _dai.IntVector_end(self)
    def rbegin(self): return _dai.IntVector_rbegin(self)
    def rend(self): return _dai.IntVector_rend(self)
    def pop_back(self): return _dai.IntVector_pop_back(self)
    def erase(self, *args): return _dai.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _dai.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _dai.IntVector_push_back(self, *args)
    def front(self): return _dai.IntVector_front(self)
    def back(self): return _dai.IntVector_back(self)
    def assign(self, *args): return _dai.IntVector_assign(self, *args)
    def resize(self, *args): return _dai.IntVector_resize(self, *args)
    def insert(self, *args): return _dai.IntVector_insert(self, *args)
    def reserve(self, *args): return _dai.IntVector_reserve(self, *args)
    def capacity(self): return _dai.IntVector_capacity(self)
    __swig_destroy__ = _dai.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _dai.IntVector_swigregister
IntVector_swigregister(IntVector)


def BigInt_size_t(*args):
  return _dai.BigInt_size_t(*args)
BigInt_size_t = _dai.BigInt_size_t

def isnan(*args):
  return _dai.isnan(*args)
isnan = _dai.isnan

def log(*args):
  return _dai.log(*args)
log = _dai.log

def log0(*args):
  return _dai.log0(*args)
log0 = _dai.log0

def exp(*args):
  return _dai.exp(*args)
exp = _dai.exp

def pow(*args):
  return _dai.pow(*args)
pow = _dai.pow

def toc():
  return _dai.toc()
toc = _dai.toc

def rnd_seed(*args):
  return _dai.rnd_seed(*args)
rnd_seed = _dai.rnd_seed

def rnd_uniform():
  return _dai.rnd_uniform()
rnd_uniform = _dai.rnd_uniform

def rnd_stdnormal():
  return _dai.rnd_stdnormal()
rnd_stdnormal = _dai.rnd_stdnormal

def rnd_int(*args):
  return _dai.rnd_int(*args)
rnd_int = _dai.rnd_int

def rnd(*args):
  return _dai.rnd(*args)
rnd = _dai.rnd

def tokenizeString(*args):
  return _dai.tokenizeString(*args)
tokenizeString = _dai.tokenizeString
NORMPROB = _dai.NORMPROB
NORMLINF = _dai.NORMLINF
DISTL1 = _dai.DISTL1
DISTLINF = _dai.DISTLINF
DISTTV = _dai.DISTTV
DISTKL = _dai.DISTKL
DISTHEL = _dai.DISTHEL
class Var:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Var, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Var, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_Var(*args)
        try: self.this.append(this)
        except: self.this = this
    def label(self): return _dai.Var_label(self)
    def states(self): return _dai.Var_states(self)
    def __lt__(self, *args): return _dai.Var___lt__(self, *args)
    def __gt__(self, *args): return _dai.Var___gt__(self, *args)
    def __le__(self, *args): return _dai.Var___le__(self, *args)
    def __ge__(self, *args): return _dai.Var___ge__(self, *args)
    def __ne__(self, *args): return _dai.Var___ne__(self, *args)
    def __eq__(self, *args): return _dai.Var___eq__(self, *args)
    def toString(self): return _dai.Var_toString(self)
    def __str__(self): return _dai.Var___str__(self)
    def __str(self): return _dai.Var___str(self)
    __swig_destroy__ = _dai.delete_Var
    __del__ = lambda self : None;
Var_swigregister = _dai.Var_swigregister
Var_swigregister(Var)

class SmallSetVar:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SmallSetVar, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SmallSetVar, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_SmallSetVar(*args)
        try: self.this.append(this)
        except: self.this = this
    def insert(self, *args): return _dai.SmallSetVar_insert(self, *args)
    def erase(self, *args): return _dai.SmallSetVar_erase(self, *args)
    def __div__(self, *args): return _dai.SmallSetVar___div__(self, *args)
    def __or__(self, *args): return _dai.SmallSetVar___or__(self, *args)
    def __and__(self, *args): return _dai.SmallSetVar___and__(self, *args)
    def __idiv__(self, *args): return _dai.SmallSetVar___idiv__(self, *args)
    def __ior__(self, *args): return _dai.SmallSetVar___ior__(self, *args)
    def __iand__(self, *args): return _dai.SmallSetVar___iand__(self, *args)
    def __lshift__(self, *args): return _dai.SmallSetVar___lshift__(self, *args)
    def __rshift__(self, *args): return _dai.SmallSetVar___rshift__(self, *args)
    def intersects(self, *args): return _dai.SmallSetVar_intersects(self, *args)
    def contains(self, *args): return _dai.SmallSetVar_contains(self, *args)
    def size(self): return _dai.SmallSetVar_size(self)
    def empty(self): return _dai.SmallSetVar_empty(self)
    def elements(self, *args): return _dai.SmallSetVar_elements(self, *args)
    def begin(self, *args): return _dai.SmallSetVar_begin(self, *args)
    def end(self, *args): return _dai.SmallSetVar_end(self, *args)
    def rbegin(self, *args): return _dai.SmallSetVar_rbegin(self, *args)
    def rend(self, *args): return _dai.SmallSetVar_rend(self, *args)
    def front(self, *args): return _dai.SmallSetVar_front(self, *args)
    def back(self, *args): return _dai.SmallSetVar_back(self, *args)
    def toString(self): return _dai.SmallSetVar_toString(self)
    def __str__(self): return _dai.SmallSetVar___str__(self)
    def __str(self): return _dai.SmallSetVar___str(self)
    __swig_destroy__ = _dai.delete_SmallSetVar
    __del__ = lambda self : None;
SmallSetVar_swigregister = _dai.SmallSetVar_swigregister
SmallSetVar_swigregister(SmallSetVar)

def __eq__(*args):
  return _dai.__eq__(*args)
__eq__ = _dai.__eq__

def __ne__(*args):
  return _dai.__ne__(*args)
__ne__ = _dai.__ne__

def __lt__(*args):
  return _dai.__lt__(*args)
__lt__ = _dai.__lt__


def calcLinearState(*args):
  return _dai.calcLinearState(*args)
calcLinearState = _dai.calcLinearState

def calcState(*args):
  return _dai.calcState(*args)
calcState = _dai.calcState
class VarSet(SmallSetVar):
    __swig_setmethods__ = {}
    for _s in [SmallSetVar]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, VarSet, name, value)
    __swig_getmethods__ = {}
    for _s in [SmallSetVar]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, VarSet, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_VarSet(*args)
        try: self.this.append(this)
        except: self.this = this
    def nrStates(self): return _dai.VarSet_nrStates(self)
    def toString(self): return _dai.VarSet_toString(self)
    def append(self, *args): return _dai.VarSet_append(self, *args)
    def __str__(self): return _dai.VarSet___str__(self)
    def __str(self): return _dai.VarSet___str(self)
    __swig_destroy__ = _dai.delete_VarSet
    __del__ = lambda self : None;
VarSet_swigregister = _dai.VarSet_swigregister
VarSet_swigregister(VarSet)

class SetVar:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SetVar, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SetVar, name)
    __repr__ = _swig_repr
    def iterator(self): return _dai.SetVar_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _dai.SetVar___nonzero__(self)
    def __bool__(self): return _dai.SetVar___bool__(self)
    def __len__(self): return _dai.SetVar___len__(self)
    def pop(self): return _dai.SetVar_pop(self)
    def __getslice__(self, *args): return _dai.SetVar___getslice__(self, *args)
    def __setslice__(self, *args): return _dai.SetVar___setslice__(self, *args)
    def __delslice__(self, *args): return _dai.SetVar___delslice__(self, *args)
    def __delitem__(self, *args): return _dai.SetVar___delitem__(self, *args)
    def __getitem__(self, *args): return _dai.SetVar___getitem__(self, *args)
    def __setitem__(self, *args): return _dai.SetVar___setitem__(self, *args)
    def append(self, *args): return _dai.SetVar_append(self, *args)
    def empty(self): return _dai.SetVar_empty(self)
    def size(self): return _dai.SetVar_size(self)
    def clear(self): return _dai.SetVar_clear(self)
    def swap(self, *args): return _dai.SetVar_swap(self, *args)
    def get_allocator(self): return _dai.SetVar_get_allocator(self)
    def begin(self): return _dai.SetVar_begin(self)
    def end(self): return _dai.SetVar_end(self)
    def rbegin(self): return _dai.SetVar_rbegin(self)
    def rend(self): return _dai.SetVar_rend(self)
    def pop_back(self): return _dai.SetVar_pop_back(self)
    def erase(self, *args): return _dai.SetVar_erase(self, *args)
    def __init__(self, *args): 
        this = _dai.new_SetVar(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _dai.SetVar_push_back(self, *args)
    def front(self): return _dai.SetVar_front(self)
    def back(self): return _dai.SetVar_back(self)
    def assign(self, *args): return _dai.SetVar_assign(self, *args)
    def resize(self, *args): return _dai.SetVar_resize(self, *args)
    def insert(self, *args): return _dai.SetVar_insert(self, *args)
    def reserve(self, *args): return _dai.SetVar_reserve(self, *args)
    def capacity(self): return _dai.SetVar_capacity(self)
    __swig_destroy__ = _dai.delete_SetVar
    __del__ = lambda self : None;
SetVar_swigregister = _dai.SetVar_swigregister
SetVar_swigregister(SetVar)

class Prob:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Prob, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Prob, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_Prob(*args)
        try: self.this.append(this)
        except: self.this = this
    def begin(self, *args): return _dai.Prob_begin(self, *args)
    def end(self, *args): return _dai.Prob_end(self, *args)
    def rbegin(self, *args): return _dai.Prob_rbegin(self, *args)
    def rend(self, *args): return _dai.Prob_rend(self, *args)
    def resize(self, *args): return _dai.Prob_resize(self, *args)
    def get(self, *args): return _dai.Prob_get(self, *args)
    def set(self, *args): return _dai.Prob_set(self, *args)
    def p(self, *args): return _dai.Prob_p(self, *args)
    def size(self): return _dai.Prob_size(self)
    def entropy(self): return _dai.Prob_entropy(self)
    def max(self): return _dai.Prob_max(self)
    def min(self): return _dai.Prob_min(self)
    def sum(self): return _dai.Prob_sum(self)
    def sumAbs(self): return _dai.Prob_sumAbs(self)
    def maxAbs(self): return _dai.Prob_maxAbs(self)
    def hasNaNs(self): return _dai.Prob_hasNaNs(self)
    def hasNegatives(self): return _dai.Prob_hasNegatives(self)
    def argmax(self): return _dai.Prob_argmax(self)
    def draw(self): return _dai.Prob_draw(self)
    def __lt__(self, *args): return _dai.Prob___lt__(self, *args)
    def __eq__(self, *args): return _dai.Prob___eq__(self, *args)
    def toString(self): return _dai.Prob_toString(self)
    def __neg__(self): return _dai.Prob___neg__(self)
    def abs(self): return _dai.Prob_abs(self)
    def exp(self): return _dai.Prob_exp(self)
    def log(self, zero=False): return _dai.Prob_log(self, zero)
    def inverse(self, zero=True): return _dai.Prob_inverse(self, zero)
    def normalized(self, *args): return _dai.Prob_normalized(self, *args)
    def randomize(self): return _dai.Prob_randomize(self)
    def setUniform(self): return _dai.Prob_setUniform(self)
    def takeAbs(self): return _dai.Prob_takeAbs(self)
    def takeExp(self): return _dai.Prob_takeExp(self)
    def takeLog(self, zero=False): return _dai.Prob_takeLog(self, zero)
    def normalize(self, *args): return _dai.Prob_normalize(self, *args)
    def fill(self, *args): return _dai.Prob_fill(self, *args)
    def __iadd__(self, *args): return _dai.Prob___iadd__(self, *args)
    def __isub__(self, *args): return _dai.Prob___isub__(self, *args)
    def __imul__(self, *args): return _dai.Prob___imul__(self, *args)
    def __idiv__(self, *args): return _dai.Prob___idiv__(self, *args)
    def divide(self, *args): return _dai.Prob_divide(self, *args)
    def __ixor__(self, *args): return _dai.Prob___ixor__(self, *args)
    def __add__(self, *args): return _dai.Prob___add__(self, *args)
    def __sub__(self, *args): return _dai.Prob___sub__(self, *args)
    def __mul__(self, *args): return _dai.Prob___mul__(self, *args)
    def __div__(self, *args): return _dai.Prob___div__(self, *args)
    def divided_by(self, *args): return _dai.Prob_divided_by(self, *args)
    def __xor__(self, *args): return _dai.Prob___xor__(self, *args)
    def __getitem__(self, *args): return _dai.Prob___getitem__(self, *args)
    def __setitem__(self, *args): return _dai.Prob___setitem__(self, *args)
    def __paren__(self, *args): return _dai.Prob___paren__(self, *args)
    def __paren_asgn__(self, *args): return _dai.Prob___paren_asgn__(self, *args)
    def __str__(self): return _dai.Prob___str__(self)
    def __str(self): return _dai.Prob___str(self)
    __swig_destroy__ = _dai.delete_Prob
    __del__ = lambda self : None;
Prob_swigregister = _dai.Prob_swigregister
Prob_swigregister(Prob)


def createFactorIsing(*args):
  return _dai.createFactorIsing(*args)
createFactorIsing = _dai.createFactorIsing

def createFactorExpGauss(*args):
  return _dai.createFactorExpGauss(*args)
createFactorExpGauss = _dai.createFactorExpGauss

def createFactorPotts(*args):
  return _dai.createFactorPotts(*args)
createFactorPotts = _dai.createFactorPotts

def createFactorDelta(*args):
  return _dai.createFactorDelta(*args)
createFactorDelta = _dai.createFactorDelta
class Factor:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Factor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Factor, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_Factor(*args)
        try: self.this.append(this)
        except: self.this = this
    def set(self, *args): return _dai.Factor_set(self, *args)
    def get(self, *args): return _dai.Factor_get(self, *args)
    def p(self, *args): return _dai.Factor_p(self, *args)
    def vars(self, *args): return _dai.Factor_vars(self, *args)
    def nrStates(self): return _dai.Factor_nrStates(self)
    def entropy(self): return _dai.Factor_entropy(self)
    def max(self): return _dai.Factor_max(self)
    def min(self): return _dai.Factor_min(self)
    def sum(self): return _dai.Factor_sum(self)
    def sumAbs(self): return _dai.Factor_sumAbs(self)
    def maxAbs(self): return _dai.Factor_maxAbs(self)
    def hasNaNs(self): return _dai.Factor_hasNaNs(self)
    def hasNegatives(self): return _dai.Factor_hasNegatives(self)
    def strength(self, *args): return _dai.Factor_strength(self, *args)
    def __eq__(self, *args): return _dai.Factor___eq__(self, *args)
    def toString(self): return _dai.Factor_toString(self)
    def __neg__(self): return _dai.Factor___neg__(self)
    def abs(self): return _dai.Factor_abs(self)
    def exp(self): return _dai.Factor_exp(self)
    def log(self, zero=False): return _dai.Factor_log(self, zero)
    def inverse(self, zero=True): return _dai.Factor_inverse(self, zero)
    def normalized(self, *args): return _dai.Factor_normalized(self, *args)
    def randomize(self): return _dai.Factor_randomize(self)
    def setUniform(self): return _dai.Factor_setUniform(self)
    def takeAbs(self): return _dai.Factor_takeAbs(self)
    def takeExp(self): return _dai.Factor_takeExp(self)
    def takeLog(self, zero=False): return _dai.Factor_takeLog(self, zero)
    def normalize(self, *args): return _dai.Factor_normalize(self, *args)
    def fill(self, *args): return _dai.Factor_fill(self, *args)
    def __ixor__(self, *args): return _dai.Factor___ixor__(self, *args)
    def __xor__(self, *args): return _dai.Factor___xor__(self, *args)
    def __iadd__(self, *args): return _dai.Factor___iadd__(self, *args)
    def __isub__(self, *args): return _dai.Factor___isub__(self, *args)
    def __imul__(self, *args): return _dai.Factor___imul__(self, *args)
    def __idiv__(self, *args): return _dai.Factor___idiv__(self, *args)
    def __add__(self, *args): return _dai.Factor___add__(self, *args)
    def __sub__(self, *args): return _dai.Factor___sub__(self, *args)
    def __mul__(self, *args): return _dai.Factor___mul__(self, *args)
    def __div__(self, *args): return _dai.Factor___div__(self, *args)
    def slice(self, *args): return _dai.Factor_slice(self, *args)
    def embed(self, *args): return _dai.Factor_embed(self, *args)
    def marginal(self, *args): return _dai.Factor_marginal(self, *args)
    def maxMarginal(self, *args): return _dai.Factor_maxMarginal(self, *args)
    def __getitem__(self, *args): return _dai.Factor___getitem__(self, *args)
    def __setitem__(self, *args): return _dai.Factor___setitem__(self, *args)
    def __paren__(self, *args): return _dai.Factor___paren__(self, *args)
    def __paren_asgn__(self, *args): return _dai.Factor___paren_asgn__(self, *args)
    def __str__(self): return _dai.Factor___str__(self)
    def __str(self): return _dai.Factor___str(self)
    __swig_destroy__ = _dai.delete_Factor
    __del__ = lambda self : None;
Factor_swigregister = _dai.Factor_swigregister
Factor_swigregister(Factor)

class VecFactor:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecFactor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecFactor, name)
    __repr__ = _swig_repr
    def iterator(self): return _dai.VecFactor_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _dai.VecFactor___nonzero__(self)
    def __bool__(self): return _dai.VecFactor___bool__(self)
    def __len__(self): return _dai.VecFactor___len__(self)
    def pop(self): return _dai.VecFactor_pop(self)
    def __getslice__(self, *args): return _dai.VecFactor___getslice__(self, *args)
    def __setslice__(self, *args): return _dai.VecFactor___setslice__(self, *args)
    def __delslice__(self, *args): return _dai.VecFactor___delslice__(self, *args)
    def __delitem__(self, *args): return _dai.VecFactor___delitem__(self, *args)
    def __getitem__(self, *args): return _dai.VecFactor___getitem__(self, *args)
    def __setitem__(self, *args): return _dai.VecFactor___setitem__(self, *args)
    def append(self, *args): return _dai.VecFactor_append(self, *args)
    def empty(self): return _dai.VecFactor_empty(self)
    def size(self): return _dai.VecFactor_size(self)
    def clear(self): return _dai.VecFactor_clear(self)
    def swap(self, *args): return _dai.VecFactor_swap(self, *args)
    def get_allocator(self): return _dai.VecFactor_get_allocator(self)
    def begin(self): return _dai.VecFactor_begin(self)
    def end(self): return _dai.VecFactor_end(self)
    def rbegin(self): return _dai.VecFactor_rbegin(self)
    def rend(self): return _dai.VecFactor_rend(self)
    def pop_back(self): return _dai.VecFactor_pop_back(self)
    def erase(self, *args): return _dai.VecFactor_erase(self, *args)
    def __init__(self, *args): 
        this = _dai.new_VecFactor(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _dai.VecFactor_push_back(self, *args)
    def front(self): return _dai.VecFactor_front(self)
    def back(self): return _dai.VecFactor_back(self)
    def assign(self, *args): return _dai.VecFactor_assign(self, *args)
    def resize(self, *args): return _dai.VecFactor_resize(self, *args)
    def insert(self, *args): return _dai.VecFactor_insert(self, *args)
    def reserve(self, *args): return _dai.VecFactor_reserve(self, *args)
    def capacity(self): return _dai.VecFactor_capacity(self)
    __swig_destroy__ = _dai.delete_VecFactor
    __del__ = lambda self : None;
VecFactor_swigregister = _dai.VecFactor_swigregister
VecFactor_swigregister(VecFactor)

class VecVecFactor:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecFactor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecFactor, name)
    __repr__ = _swig_repr
    def iterator(self): return _dai.VecVecFactor_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _dai.VecVecFactor___nonzero__(self)
    def __bool__(self): return _dai.VecVecFactor___bool__(self)
    def __len__(self): return _dai.VecVecFactor___len__(self)
    def pop(self): return _dai.VecVecFactor_pop(self)
    def __getslice__(self, *args): return _dai.VecVecFactor___getslice__(self, *args)
    def __setslice__(self, *args): return _dai.VecVecFactor___setslice__(self, *args)
    def __delslice__(self, *args): return _dai.VecVecFactor___delslice__(self, *args)
    def __delitem__(self, *args): return _dai.VecVecFactor___delitem__(self, *args)
    def __getitem__(self, *args): return _dai.VecVecFactor___getitem__(self, *args)
    def __setitem__(self, *args): return _dai.VecVecFactor___setitem__(self, *args)
    def append(self, *args): return _dai.VecVecFactor_append(self, *args)
    def empty(self): return _dai.VecVecFactor_empty(self)
    def size(self): return _dai.VecVecFactor_size(self)
    def clear(self): return _dai.VecVecFactor_clear(self)
    def swap(self, *args): return _dai.VecVecFactor_swap(self, *args)
    def get_allocator(self): return _dai.VecVecFactor_get_allocator(self)
    def begin(self): return _dai.VecVecFactor_begin(self)
    def end(self): return _dai.VecVecFactor_end(self)
    def rbegin(self): return _dai.VecVecFactor_rbegin(self)
    def rend(self): return _dai.VecVecFactor_rend(self)
    def pop_back(self): return _dai.VecVecFactor_pop_back(self)
    def erase(self, *args): return _dai.VecVecFactor_erase(self, *args)
    def __init__(self, *args): 
        this = _dai.new_VecVecFactor(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _dai.VecVecFactor_push_back(self, *args)
    def front(self): return _dai.VecVecFactor_front(self)
    def back(self): return _dai.VecVecFactor_back(self)
    def assign(self, *args): return _dai.VecVecFactor_assign(self, *args)
    def resize(self, *args): return _dai.VecVecFactor_resize(self, *args)
    def insert(self, *args): return _dai.VecVecFactor_insert(self, *args)
    def reserve(self, *args): return _dai.VecVecFactor_reserve(self, *args)
    def capacity(self): return _dai.VecVecFactor_capacity(self)
    __swig_destroy__ = _dai.delete_VecVecFactor
    __del__ = lambda self : None;
VecVecFactor_swigregister = _dai.VecVecFactor_swigregister
VecVecFactor_swigregister(VecVecFactor)

class Neighbor:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Neighbor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Neighbor, name)
    __repr__ = _swig_repr
    __swig_setmethods__["iter"] = _dai.Neighbor_iter_set
    __swig_getmethods__["iter"] = _dai.Neighbor_iter_get
    __swig_setmethods__["node"] = _dai.Neighbor_node_set
    __swig_getmethods__["node"] = _dai.Neighbor_node_get
    __swig_setmethods__["dual"] = _dai.Neighbor_dual_set
    __swig_getmethods__["dual"] = _dai.Neighbor_dual_get
    def __init__(self, *args): 
        this = _dai.new_Neighbor(*args)
        try: self.this.append(this)
        except: self.this = this
    def toInt(self): return _dai.Neighbor_toInt(self)
    __swig_destroy__ = _dai.delete_Neighbor
    __del__ = lambda self : None;
Neighbor_swigregister = _dai.Neighbor_swigregister
Neighbor_swigregister(Neighbor)

class GraphAL:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GraphAL, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GraphAL, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_GraphAL(*args)
        try: self.this.append(this)
        except: self.this = this
    def nb(self, *args): return _dai.GraphAL_nb(self, *args)
    def addNode(self): return _dai.GraphAL_addNode(self)
    def addEdge(self, *args): return _dai.GraphAL_addEdge(self, *args)
    def eraseNode(self, *args): return _dai.GraphAL_eraseNode(self, *args)
    def eraseEdge(self, *args): return _dai.GraphAL_eraseEdge(self, *args)
    def nrNodes(self): return _dai.GraphAL_nrNodes(self)
    def nrEdges(self): return _dai.GraphAL_nrEdges(self)
    def hasEdge(self, *args): return _dai.GraphAL_hasEdge(self, *args)
    def findNb(self, *args): return _dai.GraphAL_findNb(self, *args)
    def nbSet(self, *args): return _dai.GraphAL_nbSet(self, *args)
    def isConnected(self): return _dai.GraphAL_isConnected(self)
    def isTree(self): return _dai.GraphAL_isTree(self)
    def checkConsistency(self): return _dai.GraphAL_checkConsistency(self)
    def __eq__(self, *args): return _dai.GraphAL___eq__(self, *args)
    def printDot(self, *args): return _dai.GraphAL_printDot(self, *args)
    def toString(self): return _dai.GraphAL_toString(self)
    def __str__(self): return _dai.GraphAL___str__(self)
    def __str(self): return _dai.GraphAL___str(self)
    __swig_destroy__ = _dai.delete_GraphAL
    __del__ = lambda self : None;
GraphAL_swigregister = _dai.GraphAL_swigregister
GraphAL_swigregister(GraphAL)


def createGraphFull(*args):
  return _dai.createGraphFull(*args)
createGraphFull = _dai.createGraphFull

def createGraphGrid(*args):
  return _dai.createGraphGrid(*args)
createGraphGrid = _dai.createGraphGrid

def createGraphGrid3D(*args):
  return _dai.createGraphGrid3D(*args)
createGraphGrid3D = _dai.createGraphGrid3D

def createGraphLoop(*args):
  return _dai.createGraphLoop(*args)
createGraphLoop = _dai.createGraphLoop

def createGraphTree(*args):
  return _dai.createGraphTree(*args)
createGraphTree = _dai.createGraphTree

def createGraphRegular(*args):
  return _dai.createGraphRegular(*args)
createGraphRegular = _dai.createGraphRegular
class BipartiteGraph:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BipartiteGraph, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BipartiteGraph, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_BipartiteGraph(*args)
        try: self.this.append(this)
        except: self.this = this
    def nb1(self, *args): return _dai.BipartiteGraph_nb1(self, *args)
    def nb2(self, *args): return _dai.BipartiteGraph_nb2(self, *args)
    def addNode1(self): return _dai.BipartiteGraph_addNode1(self)
    def addNode2(self): return _dai.BipartiteGraph_addNode2(self)
    def addEdge(self, *args): return _dai.BipartiteGraph_addEdge(self, *args)
    def eraseNode1(self, *args): return _dai.BipartiteGraph_eraseNode1(self, *args)
    def eraseNode2(self, *args): return _dai.BipartiteGraph_eraseNode2(self, *args)
    def eraseEdge(self, *args): return _dai.BipartiteGraph_eraseEdge(self, *args)
    def nrNodes1(self): return _dai.BipartiteGraph_nrNodes1(self)
    def nrNodes2(self): return _dai.BipartiteGraph_nrNodes2(self)
    def nrEdges(self): return _dai.BipartiteGraph_nrEdges(self)
    def hasEdge(self, *args): return _dai.BipartiteGraph_hasEdge(self, *args)
    def findNb1(self, *args): return _dai.BipartiteGraph_findNb1(self, *args)
    def findNb2(self, *args): return _dai.BipartiteGraph_findNb2(self, *args)
    def nb1Set(self, *args): return _dai.BipartiteGraph_nb1Set(self, *args)
    def nb2Set(self, *args): return _dai.BipartiteGraph_nb2Set(self, *args)
    def delta1(self, *args): return _dai.BipartiteGraph_delta1(self, *args)
    def delta2(self, *args): return _dai.BipartiteGraph_delta2(self, *args)
    def isConnected(self): return _dai.BipartiteGraph_isConnected(self)
    def isTree(self): return _dai.BipartiteGraph_isTree(self)
    def __eq__(self, *args): return _dai.BipartiteGraph___eq__(self, *args)
    def checkConsistency(self): return _dai.BipartiteGraph_checkConsistency(self)
    def printDot(self, *args): return _dai.BipartiteGraph_printDot(self, *args)
    def toString(self): return _dai.BipartiteGraph_toString(self)
    def __str__(self): return _dai.BipartiteGraph___str__(self)
    def __str(self): return _dai.BipartiteGraph___str(self)
    __swig_destroy__ = _dai.delete_BipartiteGraph
    __del__ = lambda self : None;
BipartiteGraph_swigregister = _dai.BipartiteGraph_swigregister
BipartiteGraph_swigregister(BipartiteGraph)

class FactorGraph:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FactorGraph, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FactorGraph, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_FactorGraph(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _dai.delete_FactorGraph
    __del__ = lambda self : None;
    def clone(self): return _dai.FactorGraph_clone(self)
    def var(self, *args): return _dai.FactorGraph_var(self, *args)
    def vars(self): return _dai.FactorGraph_vars(self)
    def factor(self, *args): return _dai.FactorGraph_factor(self, *args)
    def factors(self): return _dai.FactorGraph_factors(self)
    def nbV(self, *args): return _dai.FactorGraph_nbV(self, *args)
    def nbF(self, *args): return _dai.FactorGraph_nbF(self, *args)
    def bipGraph(self): return _dai.FactorGraph_bipGraph(self)
    def nrVars(self): return _dai.FactorGraph_nrVars(self)
    def nrFactors(self): return _dai.FactorGraph_nrFactors(self)
    def nrEdges(self): return _dai.FactorGraph_nrEdges(self)
    def findVar(self, *args): return _dai.FactorGraph_findVar(self, *args)
    def findVars(self, *args): return _dai.FactorGraph_findVars(self, *args)
    def findFactor(self, *args): return _dai.FactorGraph_findFactor(self, *args)
    def inds2vars(self, *args): return _dai.FactorGraph_inds2vars(self, *args)
    def Delta(self, *args): return _dai.FactorGraph_Delta(self, *args)
    def delta(self, *args): return _dai.FactorGraph_delta(self, *args)
    def Deltai(self, *args): return _dai.FactorGraph_Deltai(self, *args)
    def deltai(self, *args): return _dai.FactorGraph_deltai(self, *args)
    def isConnected(self): return _dai.FactorGraph_isConnected(self)
    def isTree(self): return _dai.FactorGraph_isTree(self)
    def isPairwise(self): return _dai.FactorGraph_isPairwise(self)
    def isBinary(self): return _dai.FactorGraph_isBinary(self)
    def MarkovGraph(self): return _dai.FactorGraph_MarkovGraph(self)
    def isMaximal(self, *args): return _dai.FactorGraph_isMaximal(self, *args)
    def maximalFactor(self, *args): return _dai.FactorGraph_maximalFactor(self, *args)
    def maximalFactorDomains(self): return _dai.FactorGraph_maximalFactorDomains(self)
    def logScore(self, *args): return _dai.FactorGraph_logScore(self, *args)
    def setFactor(self, *args): return _dai.FactorGraph_setFactor(self, *args)
    def setFactors(self, *args): return _dai.FactorGraph_setFactors(self, *args)
    def backupFactor(self, *args): return _dai.FactorGraph_backupFactor(self, *args)
    def restoreFactor(self, *args): return _dai.FactorGraph_restoreFactor(self, *args)
    def backupFactors(self, *args): return _dai.FactorGraph_backupFactors(self, *args)
    def restoreFactors(self, *args): return _dai.FactorGraph_restoreFactors(self, *args)
    def maximalFactors(self): return _dai.FactorGraph_maximalFactors(self)
    def clamped(self, *args): return _dai.FactorGraph_clamped(self, *args)
    def clamp(self, *args): return _dai.FactorGraph_clamp(self, *args)
    def clampVar(self, *args): return _dai.FactorGraph_clampVar(self, *args)
    def clampFactor(self, *args): return _dai.FactorGraph_clampFactor(self, *args)
    def makeCavity(self, *args): return _dai.FactorGraph_makeCavity(self, *args)
    def makeRegionCavity(self, *args): return _dai.FactorGraph_makeRegionCavity(self, *args)
    def ReadFromFile(self, *args): return _dai.FactorGraph_ReadFromFile(self, *args)
    def WriteToFile(self, *args): return _dai.FactorGraph_WriteToFile(self, *args)
    def toString(self): return _dai.FactorGraph_toString(self)
    def fromString(self, *args): return _dai.FactorGraph_fromString(self, *args)
    def __str__(self): return _dai.FactorGraph___str__(self)
    def __str(self): return _dai.FactorGraph___str(self)
    def printDot(self, *args): return _dai.FactorGraph_printDot(self, *args)
FactorGraph_swigregister = _dai.FactorGraph_swigregister
FactorGraph_swigregister(FactorGraph)

class Region(VarSet):
    __swig_setmethods__ = {}
    for _s in [VarSet]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Region, name, value)
    __swig_getmethods__ = {}
    for _s in [VarSet]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Region, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_Region(*args)
        try: self.this.append(this)
        except: self.this = this
    def c(self, *args): return _dai.Region_c(self, *args)
    __swig_destroy__ = _dai.delete_Region
    __del__ = lambda self : None;
Region_swigregister = _dai.Region_swigregister
Region_swigregister(Region)

class FRegion(Factor):
    __swig_setmethods__ = {}
    for _s in [Factor]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FRegion, name, value)
    __swig_getmethods__ = {}
    for _s in [Factor]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, FRegion, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_FRegion(*args)
        try: self.this.append(this)
        except: self.this = this
    def c(self, *args): return _dai.FRegion_c(self, *args)
    __swig_destroy__ = _dai.delete_FRegion
    __del__ = lambda self : None;
FRegion_swigregister = _dai.FRegion_swigregister
FRegion_swigregister(FRegion)

class RegionGraph(FactorGraph):
    __swig_setmethods__ = {}
    for _s in [FactorGraph]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, RegionGraph, name, value)
    __swig_getmethods__ = {}
    for _s in [FactorGraph]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, RegionGraph, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_RegionGraph(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.RegionGraph_clone(self)
    def nrORs(self): return _dai.RegionGraph_nrORs(self)
    def nrIRs(self): return _dai.RegionGraph_nrIRs(self)
    def OR(self, *args): return _dai.RegionGraph_OR(self, *args)
    def IR(self, *args): return _dai.RegionGraph_IR(self, *args)
    def fac2OR(self, *args): return _dai.RegionGraph_fac2OR(self, *args)
    def nbOR(self, *args): return _dai.RegionGraph_nbOR(self, *args)
    def nbIR(self, *args): return _dai.RegionGraph_nbIR(self, *args)
    def DAG(self): return _dai.RegionGraph_DAG(self)
    def checkCountingNumbers(self): return _dai.RegionGraph_checkCountingNumbers(self)
    def setFactor(self, *args): return _dai.RegionGraph_setFactor(self, *args)
    def setFactors(self, *args): return _dai.RegionGraph_setFactors(self, *args)
    def ReadFromFile(self, *args): return _dai.RegionGraph_ReadFromFile(self, *args)
    def WriteToFile(self, *args): return _dai.RegionGraph_WriteToFile(self, *args)
    def toString(self): return _dai.RegionGraph_toString(self)
    def printDot(self, *args): return _dai.RegionGraph_printDot(self, *args)
    def __str__(self): return _dai.RegionGraph___str__(self)
    def __str(self): return _dai.RegionGraph___str(self)
    __swig_destroy__ = _dai.delete_RegionGraph
    __del__ = lambda self : None;
RegionGraph_swigregister = _dai.RegionGraph_swigregister
RegionGraph_swigregister(RegionGraph)


def __lshift__(*args):
  return _dai.__lshift__(*args)
__lshift__ = _dai.__lshift__
class PropertySet:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PropertySet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PropertySet, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_PropertySet(*args)
        try: self.this.append(this)
        except: self.this = this
    def set(self, *args): return _dai.PropertySet_set(self, *args)
    def __call__(self, *args): return _dai.PropertySet___call__(self, *args)
    def size(self): return _dai.PropertySet_size(self)
    def clear(self): return _dai.PropertySet_clear(self)
    def erase(self, *args): return _dai.PropertySet_erase(self, *args)
    def hasKey(self, *args): return _dai.PropertySet_hasKey(self, *args)
    def keys(self): return _dai.PropertySet_keys(self)
    def get(self, *args): return _dai.PropertySet_get(self, *args)
    def toString(self): return _dai.PropertySet_toString(self)
    def fromString(self, *args): return _dai.PropertySet_fromString(self, *args)
    def __setitem__(self, *args): return _dai.PropertySet___setitem__(self, *args)
    def __str__(self): return _dai.PropertySet___str__(self)
    def __str(self): return _dai.PropertySet___str(self)
    __swig_destroy__ = _dai.delete_PropertySet
    __del__ = lambda self : None;
PropertySet_swigregister = _dai.PropertySet_swigregister
PropertySet_swigregister(PropertySet)

class IndexFor:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IndexFor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IndexFor, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_IndexFor(*args)
        try: self.this.append(this)
        except: self.this = this
    def reset(self): return _dai.IndexFor_reset(self)
    def toInt(self): return _dai.IndexFor_toInt(self)
    def valid(self): return _dai.IndexFor_valid(self)
    def next(self): return _dai.IndexFor_next(self)
    __swig_destroy__ = _dai.delete_IndexFor
    __del__ = lambda self : None;
IndexFor_swigregister = _dai.IndexFor_swigregister
IndexFor_swigregister(IndexFor)

class Permute:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Permute, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Permute, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_Permute(*args)
        try: self.this.append(this)
        except: self.this = this
    def convertLinearIndex(self, *args): return _dai.Permute_convertLinearIndex(self, *args)
    def sigma(self, *args): return _dai.Permute_sigma(self, *args)
    def ranges(self): return _dai.Permute_ranges(self)
    def inverse(self): return _dai.Permute_inverse(self)
    def __getitem__(self, *args): return _dai.Permute___getitem__(self, *args)
    def __paren__(self, *args): return _dai.Permute___paren__(self, *args)
    __swig_destroy__ = _dai.delete_Permute
    __del__ = lambda self : None;
Permute_swigregister = _dai.Permute_swigregister
Permute_swigregister(Permute)

class multifor:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, multifor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, multifor, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_multifor(*args)
        try: self.this.append(this)
        except: self.this = this
    def toInt(self): return _dai.multifor_toInt(self)
    def reset(self): return _dai.multifor_reset(self)
    def valid(self): return _dai.multifor_valid(self)
    def next(self): return _dai.multifor_next(self)
    def __getitem__(self, *args): return _dai.multifor___getitem__(self, *args)
    def __paren__(self, *args): return _dai.multifor___paren__(self, *args)
    __swig_destroy__ = _dai.delete_multifor
    __del__ = lambda self : None;
multifor_swigregister = _dai.multifor_swigregister
multifor_swigregister(multifor)

class State:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, State, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, State, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_State(*args)
        try: self.this.append(this)
        except: self.this = this
    def begin(self): return _dai.State_begin(self)
    def end(self): return _dai.State_end(self)
    def toInt(self): return _dai.State_toInt(self)
    def get(self): return _dai.State_get(self)
    def __call__(self, *args): return _dai.State___call__(self, *args)
    def valid(self): return _dai.State_valid(self)
    def reset(self): return _dai.State_reset(self)
    def next(self): return _dai.State_next(self)
    __swig_destroy__ = _dai.delete_State
    __del__ = lambda self : None;
State_swigregister = _dai.State_swigregister
State_swigregister(State)

class InfAlg:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, InfAlg, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, InfAlg, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dai.delete_InfAlg
    __del__ = lambda self : None;
    def clone(self): return _dai.InfAlg_clone(self)
    def construct(self, *args): return _dai.InfAlg_construct(self, *args)
    def name(self): return _dai.InfAlg_name(self)
    def identify(self): return _dai.InfAlg_identify(self)
    def fg(self, *args): return _dai.InfAlg_fg(self, *args)
    def init(self, *args): return _dai.InfAlg_init(self, *args)
    def run(self): return _dai.InfAlg_run(self)
    def belief(self, *args): return _dai.InfAlg_belief(self, *args)
    def beliefV(self, *args): return _dai.InfAlg_beliefV(self, *args)
    def beliefF(self, *args): return _dai.InfAlg_beliefF(self, *args)
    def beliefs(self): return _dai.InfAlg_beliefs(self)
    def logZ(self): return _dai.InfAlg_logZ(self)
    def findMaximum(self): return _dai.InfAlg_findMaximum(self)
    def maxDiff(self): return _dai.InfAlg_maxDiff(self)
    def Iterations(self): return _dai.InfAlg_Iterations(self)
    def setMaxIter(self, *args): return _dai.InfAlg_setMaxIter(self, *args)
    def clamp(self, *args): return _dai.InfAlg_clamp(self, *args)
    def makeCavity(self, *args): return _dai.InfAlg_makeCavity(self, *args)
    def makeRegionCavity(self, *args): return _dai.InfAlg_makeRegionCavity(self, *args)
    def backupFactor(self, *args): return _dai.InfAlg_backupFactor(self, *args)
    def backupFactors(self, *args): return _dai.InfAlg_backupFactors(self, *args)
    def restoreFactor(self, *args): return _dai.InfAlg_restoreFactor(self, *args)
    def restoreFactors(self, *args): return _dai.InfAlg_restoreFactors(self, *args)
    def setProperties(self, *args): return _dai.InfAlg_setProperties(self, *args)
    def getProperties(self): return _dai.InfAlg_getProperties(self)
    def printProperties(self): return _dai.InfAlg_printProperties(self)
InfAlg_swigregister = _dai.InfAlg_swigregister
InfAlg_swigregister(InfAlg)


def calcMarginal(*args):
  return _dai.calcMarginal(*args)
calcMarginal = _dai.calcMarginal

def calcPairBeliefs(*args):
  return _dai.calcPairBeliefs(*args)
calcPairBeliefs = _dai.calcPairBeliefs

def findMaximum(*args):
  return _dai.findMaximum(*args)
findMaximum = _dai.findMaximum

def builtinInfAlgs():
  return _dai.builtinInfAlgs()
builtinInfAlgs = _dai.builtinInfAlgs

def builtinInfAlgNames():
  return _dai.builtinInfAlgNames()
builtinInfAlgNames = _dai.builtinInfAlgNames

def newInfAlg(*args):
  return _dai.newInfAlg(*args)
newInfAlg = _dai.newInfAlg

def newInfAlgFromString(*args):
  return _dai.newInfAlgFromString(*args)
newInfAlgFromString = _dai.newInfAlgFromString

def parseNameProperties(*args):
  return _dai.parseNameProperties(*args)
parseNameProperties = _dai.parseNameProperties

def readAliasesFile(*args):
  return _dai.readAliasesFile(*args)
readAliasesFile = _dai.readAliasesFile
class DictStrStr:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DictStrStr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DictStrStr, name)
    __repr__ = _swig_repr
    def iterator(self): return _dai.DictStrStr_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _dai.DictStrStr___nonzero__(self)
    def __bool__(self): return _dai.DictStrStr___bool__(self)
    def __len__(self): return _dai.DictStrStr___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _dai.DictStrStr___getitem__(self, *args)
    def __delitem__(self, *args): return _dai.DictStrStr___delitem__(self, *args)
    def has_key(self, *args): return _dai.DictStrStr_has_key(self, *args)
    def keys(self): return _dai.DictStrStr_keys(self)
    def values(self): return _dai.DictStrStr_values(self)
    def items(self): return _dai.DictStrStr_items(self)
    def __contains__(self, *args): return _dai.DictStrStr___contains__(self, *args)
    def key_iterator(self): return _dai.DictStrStr_key_iterator(self)
    def value_iterator(self): return _dai.DictStrStr_value_iterator(self)
    def __setitem__(self, *args): return _dai.DictStrStr___setitem__(self, *args)
    def asdict(self): return _dai.DictStrStr_asdict(self)
    def __init__(self, *args): 
        this = _dai.new_DictStrStr(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _dai.DictStrStr_empty(self)
    def size(self): return _dai.DictStrStr_size(self)
    def clear(self): return _dai.DictStrStr_clear(self)
    def swap(self, *args): return _dai.DictStrStr_swap(self, *args)
    def get_allocator(self): return _dai.DictStrStr_get_allocator(self)
    def begin(self): return _dai.DictStrStr_begin(self)
    def end(self): return _dai.DictStrStr_end(self)
    def rbegin(self): return _dai.DictStrStr_rbegin(self)
    def rend(self): return _dai.DictStrStr_rend(self)
    def count(self, *args): return _dai.DictStrStr_count(self, *args)
    def erase(self, *args): return _dai.DictStrStr_erase(self, *args)
    def find(self, *args): return _dai.DictStrStr_find(self, *args)
    def lower_bound(self, *args): return _dai.DictStrStr_lower_bound(self, *args)
    def upper_bound(self, *args): return _dai.DictStrStr_upper_bound(self, *args)
    __swig_destroy__ = _dai.delete_DictStrStr
    __del__ = lambda self : None;
DictStrStr_swigregister = _dai.DictStrStr_swigregister
DictStrStr_swigregister(DictStrStr)

class PairStrPropSet:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairStrPropSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PairStrPropSet, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_PairStrPropSet(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["first"] = _dai.PairStrPropSet_first_set
    __swig_getmethods__["first"] = _dai.PairStrPropSet_first_get
    __swig_setmethods__["second"] = _dai.PairStrPropSet_second_set
    __swig_getmethods__["second"] = _dai.PairStrPropSet_second_get
    def __len__(self): return 2
    def __repr__(self): return str((self.first, self.second))
    def __getitem__(self, index): 
      if not (index % 2): 
        return self.first
      else:
        return self.second
    def __setitem__(self, index, val):
      if not (index % 2): 
        self.first = val
      else:
        self.second = val
    __swig_destroy__ = _dai.delete_PairStrPropSet
    __del__ = lambda self : None;
PairStrPropSet_swigregister = _dai.PairStrPropSet_swigregister
PairStrPropSet_swigregister(PairStrPropSet)

class BP:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BP, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BP, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.BP_props_set
    __swig_getmethods__["props"] = _dai.BP_props_get
    __swig_setmethods__["recordSentMessages"] = _dai.BP_recordSentMessages_set
    __swig_getmethods__["recordSentMessages"] = _dai.BP_recordSentMessages_get
    def __init__(self, *args): 
        this = _dai.new_BP(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.BP_clone(self)
    def construct(self, *args): return _dai.BP_construct(self, *args)
    def name(self): return _dai.BP_name(self)
    def belief(self, *args): return _dai.BP_belief(self, *args)
    def beliefV(self, *args): return _dai.BP_beliefV(self, *args)
    def beliefF(self, *args): return _dai.BP_beliefF(self, *args)
    def beliefs(self): return _dai.BP_beliefs(self)
    def logZ(self): return _dai.BP_logZ(self)
    def findMaximum(self): return _dai.BP_findMaximum(self)
    def init(self, *args): return _dai.BP_init(self, *args)
    def run(self): return _dai.BP_run(self)
    def maxDiff(self): return _dai.BP_maxDiff(self)
    def Iterations(self): return _dai.BP_Iterations(self)
    def setMaxIter(self, *args): return _dai.BP_setMaxIter(self, *args)
    def setProperties(self, *args): return _dai.BP_setProperties(self, *args)
    def getProperties(self): return _dai.BP_getProperties(self)
    def printProperties(self): return _dai.BP_printProperties(self)
    def getSentMessages(self): return _dai.BP_getSentMessages(self)
    def clearSentMessages(self): return _dai.BP_clearSentMessages(self)
    __swig_destroy__ = _dai.delete_BP
    __del__ = lambda self : None;
BP_swigregister = _dai.BP_swigregister
BP_swigregister(BP)

class FBP(BP):
    __swig_setmethods__ = {}
    for _s in [BP]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FBP, name, value)
    __swig_getmethods__ = {}
    for _s in [BP]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, FBP, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_FBP(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.FBP_clone(self)
    def construct(self, *args): return _dai.FBP_construct(self, *args)
    def name(self): return _dai.FBP_name(self)
    def logZ(self): return _dai.FBP_logZ(self)
    def Weight(self, *args): return _dai.FBP_Weight(self, *args)
    def Weights(self): return _dai.FBP_Weights(self)
    def setWeight(self, *args): return _dai.FBP_setWeight(self, *args)
    def setWeights(self, *args): return _dai.FBP_setWeights(self, *args)
    __swig_destroy__ = _dai.delete_FBP
    __del__ = lambda self : None;
FBP_swigregister = _dai.FBP_swigregister
FBP_swigregister(FBP)

class TRWBP(BP):
    __swig_setmethods__ = {}
    for _s in [BP]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TRWBP, name, value)
    __swig_getmethods__ = {}
    for _s in [BP]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TRWBP, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nrtrees"] = _dai.TRWBP_nrtrees_set
    __swig_getmethods__["nrtrees"] = _dai.TRWBP_nrtrees_get
    def __init__(self, *args): 
        this = _dai.new_TRWBP(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.TRWBP_clone(self)
    def construct(self, *args): return _dai.TRWBP_construct(self, *args)
    def name(self): return _dai.TRWBP_name(self)
    def logZ(self): return _dai.TRWBP_logZ(self)
    def setProperties(self, *args): return _dai.TRWBP_setProperties(self, *args)
    def getProperties(self): return _dai.TRWBP_getProperties(self)
    def printProperties(self): return _dai.TRWBP_printProperties(self)
    def Weight(self, *args): return _dai.TRWBP_Weight(self, *args)
    def Weights(self): return _dai.TRWBP_Weights(self)
    def setWeight(self, *args): return _dai.TRWBP_setWeight(self, *args)
    def setWeights(self, *args): return _dai.TRWBP_setWeights(self, *args)
    def addTreeToWeights(self, *args): return _dai.TRWBP_addTreeToWeights(self, *args)
    def sampleWeights(self, *args): return _dai.TRWBP_sampleWeights(self, *args)
    __swig_destroy__ = _dai.delete_TRWBP
    __del__ = lambda self : None;
TRWBP_swigregister = _dai.TRWBP_swigregister
TRWBP_swigregister(TRWBP)

class MF:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MF, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MF, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.MF_props_set
    __swig_getmethods__["props"] = _dai.MF_props_get
    def __init__(self, *args): 
        this = _dai.new_MF(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.MF_clone(self)
    def construct(self, *args): return _dai.MF_construct(self, *args)
    def name(self): return _dai.MF_name(self)
    def belief(self, *args): return _dai.MF_belief(self, *args)
    def beliefV(self, *args): return _dai.MF_beliefV(self, *args)
    def beliefs(self): return _dai.MF_beliefs(self)
    def logZ(self): return _dai.MF_logZ(self)
    def init(self, *args): return _dai.MF_init(self, *args)
    def run(self): return _dai.MF_run(self)
    def maxDiff(self): return _dai.MF_maxDiff(self)
    def Iterations(self): return _dai.MF_Iterations(self)
    def setMaxIter(self, *args): return _dai.MF_setMaxIter(self, *args)
    def setProperties(self, *args): return _dai.MF_setProperties(self, *args)
    def getProperties(self): return _dai.MF_getProperties(self)
    def printProperties(self): return _dai.MF_printProperties(self)
    __swig_destroy__ = _dai.delete_MF
    __del__ = lambda self : None;
MF_swigregister = _dai.MF_swigregister
MF_swigregister(MF)

class HAK:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HAK, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HAK, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.HAK_props_set
    __swig_getmethods__["props"] = _dai.HAK_props_get
    def __init__(self, *args): 
        this = _dai.new_HAK(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.HAK_clone(self)
    def construct(self, *args): return _dai.HAK_construct(self, *args)
    def name(self): return _dai.HAK_name(self)
    def belief(self, *args): return _dai.HAK_belief(self, *args)
    def beliefs(self): return _dai.HAK_beliefs(self)
    def logZ(self): return _dai.HAK_logZ(self)
    def init(self, *args): return _dai.HAK_init(self, *args)
    def run(self): return _dai.HAK_run(self)
    def maxDiff(self): return _dai.HAK_maxDiff(self)
    def Iterations(self): return _dai.HAK_Iterations(self)
    def setMaxIter(self, *args): return _dai.HAK_setMaxIter(self, *args)
    def setProperties(self, *args): return _dai.HAK_setProperties(self, *args)
    def getProperties(self): return _dai.HAK_getProperties(self)
    def printProperties(self): return _dai.HAK_printProperties(self)
    def muab(self, *args): return _dai.HAK_muab(self, *args)
    def muba(self, *args): return _dai.HAK_muba(self, *args)
    def Qa(self, *args): return _dai.HAK_Qa(self, *args)
    def Qb(self, *args): return _dai.HAK_Qb(self, *args)
    def doGBP(self): return _dai.HAK_doGBP(self)
    def doDoubleLoop(self): return _dai.HAK_doDoubleLoop(self)
    __swig_destroy__ = _dai.delete_HAK
    __del__ = lambda self : None;
HAK_swigregister = _dai.HAK_swigregister
HAK_swigregister(HAK)

class LC:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LC, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.LC_props_set
    __swig_getmethods__["props"] = _dai.LC_props_get
    def __init__(self, *args): 
        this = _dai.new_LC(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.LC_clone(self)
    def construct(self, *args): return _dai.LC_construct(self, *args)
    def name(self): return _dai.LC_name(self)
    def belief(self, *args): return _dai.LC_belief(self, *args)
    def beliefV(self, *args): return _dai.LC_beliefV(self, *args)
    def beliefs(self): return _dai.LC_beliefs(self)
    def logZ(self): return _dai.LC_logZ(self)
    def init(self, *args): return _dai.LC_init(self, *args)
    def run(self): return _dai.LC_run(self)
    def maxDiff(self): return _dai.LC_maxDiff(self)
    def Iterations(self): return _dai.LC_Iterations(self)
    def setMaxIter(self, *args): return _dai.LC_setMaxIter(self, *args)
    def setProperties(self, *args): return _dai.LC_setProperties(self, *args)
    def getProperties(self): return _dai.LC_getProperties(self)
    def printProperties(self): return _dai.LC_printProperties(self)
    def CalcCavityDist(self, *args): return _dai.LC_CalcCavityDist(self, *args)
    def InitCavityDists(self, *args): return _dai.LC_InitCavityDists(self, *args)
    def SetCavityDists(self, *args): return _dai.LC_SetCavityDists(self, *args)
    def NewPancake(self, *args): return _dai.LC_NewPancake(self, *args)
    def CalcBelief(self, *args): return _dai.LC_CalcBelief(self, *args)
    def pancake(self, *args): return _dai.LC_pancake(self, *args)
    def cavitydist(self, *args): return _dai.LC_cavitydist(self, *args)
    __swig_destroy__ = _dai.delete_LC
    __del__ = lambda self : None;
LC_swigregister = _dai.LC_swigregister
LC_swigregister(LC)

class JTree:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, JTree, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, JTree, name)
    __repr__ = _swig_repr
    __swig_setmethods__["RTree"] = _dai.JTree_RTree_set
    __swig_getmethods__["RTree"] = _dai.JTree_RTree_get
    __swig_setmethods__["Qa"] = _dai.JTree_Qa_set
    __swig_getmethods__["Qa"] = _dai.JTree_Qa_get
    __swig_setmethods__["Qb"] = _dai.JTree_Qb_set
    __swig_getmethods__["Qb"] = _dai.JTree_Qb_get
    __swig_setmethods__["props"] = _dai.JTree_props_set
    __swig_getmethods__["props"] = _dai.JTree_props_get
    def __init__(self, *args): 
        this = _dai.new_JTree(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.JTree_clone(self)
    def name(self): return _dai.JTree_name(self)
    def belief(self, *args): return _dai.JTree_belief(self, *args)
    def beliefs(self): return _dai.JTree_beliefs(self)
    def logZ(self): return _dai.JTree_logZ(self)
    def findMaximum(self): return _dai.JTree_findMaximum(self)
    def init(self, *args): return _dai.JTree_init(self, *args)
    def run(self): return _dai.JTree_run(self)
    def maxDiff(self): return _dai.JTree_maxDiff(self)
    def Iterations(self): return _dai.JTree_Iterations(self)
    def setProperties(self, *args): return _dai.JTree_setProperties(self, *args)
    def getProperties(self): return _dai.JTree_getProperties(self)
    def printProperties(self): return _dai.JTree_printProperties(self)
    def construct(self, *args): return _dai.JTree_construct(self, *args)
    def GenerateJT(self, *args): return _dai.JTree_GenerateJT(self, *args)
    def message(self, *args): return _dai.JTree_message(self, *args)
    def runHUGIN(self): return _dai.JTree_runHUGIN(self)
    def runShaferShenoy(self): return _dai.JTree_runShaferShenoy(self)
    def findEfficientTree(self, *args): return _dai.JTree_findEfficientTree(self, *args)
    def calcMarginal(self, *args): return _dai.JTree_calcMarginal(self, *args)
    __swig_destroy__ = _dai.delete_JTree
    __del__ = lambda self : None;
JTree_swigregister = _dai.JTree_swigregister
JTree_swigregister(JTree)


def boundTreewidth(*args):
  return _dai.boundTreewidth(*args)
boundTreewidth = _dai.boundTreewidth
class TreeEP(JTree):
    __swig_setmethods__ = {}
    for _s in [JTree]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TreeEP, name, value)
    __swig_getmethods__ = {}
    for _s in [JTree]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TreeEP, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.TreeEP_props_set
    __swig_getmethods__["props"] = _dai.TreeEP_props_get
    def __init__(self, *args): 
        this = _dai.new_TreeEP(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.TreeEP_clone(self)
    def construct(self, *args): return _dai.TreeEP_construct(self, *args)
    def name(self): return _dai.TreeEP_name(self)
    def logZ(self): return _dai.TreeEP_logZ(self)
    def init(self, *args): return _dai.TreeEP_init(self, *args)
    def run(self): return _dai.TreeEP_run(self)
    def maxDiff(self): return _dai.TreeEP_maxDiff(self)
    def Iterations(self): return _dai.TreeEP_Iterations(self)
    def setMaxIter(self, *args): return _dai.TreeEP_setMaxIter(self, *args)
    def setProperties(self, *args): return _dai.TreeEP_setProperties(self, *args)
    def getProperties(self): return _dai.TreeEP_getProperties(self)
    def printProperties(self): return _dai.TreeEP_printProperties(self)
    __swig_destroy__ = _dai.delete_TreeEP
    __del__ = lambda self : None;
TreeEP_swigregister = _dai.TreeEP_swigregister
TreeEP_swigregister(TreeEP)

class MR:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MR, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MR, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.MR_props_set
    __swig_getmethods__["props"] = _dai.MR_props_get
    def __init__(self, *args): 
        this = _dai.new_MR(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.MR_clone(self)
    def construct(self, *args): return _dai.MR_construct(self, *args)
    def name(self): return _dai.MR_name(self)
    def belief(self, *args): return _dai.MR_belief(self, *args)
    def beliefV(self, *args): return _dai.MR_beliefV(self, *args)
    def beliefs(self): return _dai.MR_beliefs(self)
    def logZ(self): return _dai.MR_logZ(self)
    def init(self, *args): return _dai.MR_init(self, *args)
    def run(self): return _dai.MR_run(self)
    def maxDiff(self): return _dai.MR_maxDiff(self)
    def Iterations(self): return _dai.MR_Iterations(self)
    def setProperties(self, *args): return _dai.MR_setProperties(self, *args)
    def getProperties(self): return _dai.MR_getProperties(self)
    def printProperties(self): return _dai.MR_printProperties(self)
    __swig_destroy__ = _dai.delete_MR
    __del__ = lambda self : None;
MR_swigregister = _dai.MR_swigregister
MR_swigregister(MR)

class Gibbs:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Gibbs, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Gibbs, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.Gibbs_props_set
    __swig_getmethods__["props"] = _dai.Gibbs_props_get
    def __init__(self, *args): 
        this = _dai.new_Gibbs(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.Gibbs_clone(self)
    def construct(self, *args): return _dai.Gibbs_construct(self, *args)
    def name(self): return _dai.Gibbs_name(self)
    def belief(self, *args): return _dai.Gibbs_belief(self, *args)
    def beliefV(self, *args): return _dai.Gibbs_beliefV(self, *args)
    def beliefF(self, *args): return _dai.Gibbs_beliefF(self, *args)
    def beliefs(self): return _dai.Gibbs_beliefs(self)
    def logZ(self): return _dai.Gibbs_logZ(self)
    def findMaximum(self): return _dai.Gibbs_findMaximum(self)
    def init(self, *args): return _dai.Gibbs_init(self, *args)
    def run(self): return _dai.Gibbs_run(self)
    def maxDiff(self): return _dai.Gibbs_maxDiff(self)
    def Iterations(self): return _dai.Gibbs_Iterations(self)
    def setMaxIter(self, *args): return _dai.Gibbs_setMaxIter(self, *args)
    def setProperties(self, *args): return _dai.Gibbs_setProperties(self, *args)
    def getProperties(self): return _dai.Gibbs_getProperties(self)
    def printProperties(self): return _dai.Gibbs_printProperties(self)
    def randomizeState(self): return _dai.Gibbs_randomizeState(self)
    def state(self, *args): return _dai.Gibbs_state(self, *args)
    __swig_destroy__ = _dai.delete_Gibbs
    __del__ = lambda self : None;
Gibbs_swigregister = _dai.Gibbs_swigregister
Gibbs_swigregister(Gibbs)


def getGibbsState(*args):
  return _dai.getGibbsState(*args)
getGibbsState = _dai.getGibbsState
class CBP:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CBP, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CBP, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _dai.new_CBP(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.CBP_clone(self)
    def construct(self, *args): return _dai.CBP_construct(self, *args)
    def name(self): return _dai.CBP_name(self)
    def belief(self, *args): return _dai.CBP_belief(self, *args)
    def beliefV(self, *args): return _dai.CBP_beliefV(self, *args)
    def beliefF(self, *args): return _dai.CBP_beliefF(self, *args)
    def beliefs(self): return _dai.CBP_beliefs(self)
    def logZ(self): return _dai.CBP_logZ(self)
    def init(self, *args): return _dai.CBP_init(self, *args)
    def run(self): return _dai.CBP_run(self)
    def maxDiff(self): return _dai.CBP_maxDiff(self)
    def Iterations(self): return _dai.CBP_Iterations(self)
    def setMaxIter(self, *args): return _dai.CBP_setMaxIter(self, *args)
    def setProperties(self, *args): return _dai.CBP_setProperties(self, *args)
    def getProperties(self): return _dai.CBP_getProperties(self)
    def printProperties(self): return _dai.CBP_printProperties(self)
    __swig_setmethods__["props"] = _dai.CBP_props_set
    __swig_getmethods__["props"] = _dai.CBP_props_get
    __swig_destroy__ = _dai.delete_CBP
    __del__ = lambda self : None;
CBP_swigregister = _dai.CBP_swigregister
CBP_swigregister(CBP)


def BBPFindClampVar(*args):
  return _dai.BBPFindClampVar(*args)
BBPFindClampVar = _dai.BBPFindClampVar
class DecMAP:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DecMAP, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DecMAP, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.DecMAP_props_set
    __swig_getmethods__["props"] = _dai.DecMAP_props_get
    def __init__(self, *args): 
        this = _dai.new_DecMAP(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.DecMAP_clone(self)
    def construct(self, *args): return _dai.DecMAP_construct(self, *args)
    def name(self): return _dai.DecMAP_name(self)
    def belief(self, *args): return _dai.DecMAP_belief(self, *args)
    def beliefV(self, *args): return _dai.DecMAP_beliefV(self, *args)
    def beliefF(self, *args): return _dai.DecMAP_beliefF(self, *args)
    def beliefs(self): return _dai.DecMAP_beliefs(self)
    def logZ(self): return _dai.DecMAP_logZ(self)
    def findMaximum(self): return _dai.DecMAP_findMaximum(self)
    def init(self, *args): return _dai.DecMAP_init(self, *args)
    def run(self): return _dai.DecMAP_run(self)
    def maxDiff(self): return _dai.DecMAP_maxDiff(self)
    def Iterations(self): return _dai.DecMAP_Iterations(self)
    def setProperties(self, *args): return _dai.DecMAP_setProperties(self, *args)
    def getProperties(self): return _dai.DecMAP_getProperties(self)
    def printProperties(self): return _dai.DecMAP_printProperties(self)
    __swig_destroy__ = _dai.delete_DecMAP
    __del__ = lambda self : None;
DecMAP_swigregister = _dai.DecMAP_swigregister
DecMAP_swigregister(DecMAP)

class Cobweb:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cobweb, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cobweb, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cav"] = _dai.Cobweb_cav_set
    __swig_getmethods__["cav"] = _dai.Cobweb_cav_get
    __swig_setmethods__["_g2l"] = _dai.Cobweb__g2l_set
    __swig_getmethods__["_g2l"] = _dai.Cobweb__g2l_get
    def __init__(self, *args): 
        this = _dai.new_Cobweb(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _dai.delete_Cobweb
    __del__ = lambda self : None;
    def setInfAlg(self, *args): return _dai.Cobweb_setInfAlg(self, *args)
    def factor(self, *args): return _dai.Cobweb_factor(self, *args)
    def initialize(self): return _dai.Cobweb_initialize(self)
    def marginal(self, *args): return _dai.Cobweb_marginal(self, *args)
    def updateFactor(self, *args): return _dai.Cobweb_updateFactor(self, *args)
    def belief(self, *args): return _dai.Cobweb_belief(self, *args)
Cobweb_swigregister = _dai.Cobweb_swigregister
Cobweb_swigregister(Cobweb)

class GLC:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GLC, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GLC, name)
    __repr__ = _swig_repr
    __swig_setmethods__["props"] = _dai.GLC_props_set
    __swig_getmethods__["props"] = _dai.GLC_props_get
    def __init__(self, *args): 
        this = _dai.new_GLC(*args)
        try: self.this.append(this)
        except: self.this = this
    def clone(self): return _dai.GLC_clone(self)
    def construct(self, *args): return _dai.GLC_construct(self, *args)
    def name(self): return _dai.GLC_name(self)
    def belief(self, *args): return _dai.GLC_belief(self, *args)
    def beliefV(self, *args): return _dai.GLC_beliefV(self, *args)
    def beliefs(self): return _dai.GLC_beliefs(self)
    def logZ(self): return _dai.GLC_logZ(self)
    def init(self, *args): return _dai.GLC_init(self, *args)
    def run(self): return _dai.GLC_run(self)
    def maxDiff(self): return _dai.GLC_maxDiff(self)
    def Iterations(self): return _dai.GLC_Iterations(self)
    def setMaxIter(self, *args): return _dai.GLC_setMaxIter(self, *args)
    def setProperties(self, *args): return _dai.GLC_setProperties(self, *args)
    def getProperties(self): return _dai.GLC_getProperties(self)
    def printProperties(self): return _dai.GLC_printProperties(self)
    def CW(self, *args): return _dai.GLC_CW(self, *args)
    def CalcCavityDist(self, *args): return _dai.GLC_CalcCavityDist(self, *args)
    def InitCavityDists(self, *args): return _dai.GLC_InitCavityDists(self, *args)
    def NewPancake(self, *args): return _dai.GLC_NewPancake(self, *args)
    def OVNewPancake(self, *args): return _dai.GLC_OVNewPancake(self, *args)
    def CalcBelief(self, *args): return _dai.GLC_CalcBelief(self, *args)
    def CalcFactorBelief(self, *args): return _dai.GLC_CalcFactorBelief(self, *args)
    def calcRegions(self): return _dai.GLC_calcRegions(self)
    def initCWs(self): return _dai.GLC_initCWs(self)
    def setCWs(self, *args): return _dai.GLC_setCWs(self, *args)
    def findLoopClusters(self, *args): return _dai.GLC_findLoopClusters(self, *args)
    def findOVLoopClusters(self, *args): return _dai.GLC_findOVLoopClusters(self, *args)
    __swig_destroy__ = _dai.delete_GLC
    __del__ = lambda self : None;
GLC_swigregister = _dai.GLC_swigregister
GLC_swigregister(GLC)

# This file is compatible with both classic and new-style classes.


